---
- name: Deploy MySQL on mysql-container
  hosts: mysql
  become: yes
  tasks:
  # Start time
  - name: Record start time
    command: date +%s
    register: start_time
    delegate_to: localhost
    become: no

  # Install Python and required dependencies
  - name: Install Python and required packages
    apt:
      name:
      - python3
      - python3-pip
      - python3-pymysql
      state: present
      update_cache: yes

  # MySQL container installation
  - name: Install MySQL on mysql-container
    block:
    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes
    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes
    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "######"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: "######"
        state: present

  # End time
  - name: Record end time
    command: date +%s
    register: end_time
    delegate_to: localhost
    become: no

  # Output time
  - name: Show execution time
    debug:
      msg: "MySQL installation time: {{ (end_time.stdout | int - start_time.stdout | int) }} seconds"
  - name: Log execution time
    lineinfile:
      path: ansible_time.log
      line: "MySQL installation time: {{ (end_time.stdout | int - start_time.stdout | int) }} seconds"
      create: yes
      delegate_to: localhost
      become: no
